-- Étiquettes (tags) : nouvelle entité + relation plusieurs-à-plusieurs avec les recettes.
-- Demandée explicitement par le client ; utilisée par la barre de filtres, les lignes
-- de la liste dense, les cartes de la grille et la feuille de filtres mobile.
--
-- Conventions reprises telles quelles des tables existantes :
--   - identifiants `bigint generated by default as identity` (comme recettes et books)
--   - RLS : lecture publique (la famille consulte sans compte), écriture authentifiée
-- Le script est réexécutable : chaque objet est créé de façon idempotente et les
-- politiques sont supprimées avant recréation (CREATE POLICY n'accepte pas IF NOT EXISTS).

CREATE TABLE IF NOT EXISTS etiquettes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

-- Un nom d'étiquette est unique indépendamment de la casse et des espaces de bord,
-- pour éviter que « Souper », « souper » et « souper  » coexistent.
CREATE UNIQUE INDEX IF NOT EXISTS idx_etiquettes_name_unique
    ON etiquettes (lower(btrim(name)));

CREATE TABLE IF NOT EXISTS recettes_etiquettes (
    recette_id bigint NOT NULL REFERENCES recettes (id) ON DELETE CASCADE,
    etiquette_id bigint NOT NULL REFERENCES etiquettes (id) ON DELETE CASCADE,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (recette_id, etiquette_id)
);

-- La clé primaire couvre déjà (recette_id, etiquette_id) ; l'index inverse sert au
-- filtrage « toutes les recettes portant cette étiquette ».
CREATE INDEX IF NOT EXISTS idx_recettes_etiquettes_etiquette_id
    ON recettes_etiquettes (etiquette_id);

ALTER TABLE etiquettes ENABLE ROW LEVEL SECURITY;
ALTER TABLE recettes_etiquettes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Enable read access for all users" ON etiquettes;
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON etiquettes;
DROP POLICY IF EXISTS "Update etiquettes" ON etiquettes;
DROP POLICY IF EXISTS "Delete etiquettes" ON etiquettes;

CREATE POLICY "Enable read access for all users" ON etiquettes
    FOR SELECT TO public USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON etiquettes
    FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Update etiquettes" ON etiquettes
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Delete etiquettes" ON etiquettes
    FOR DELETE TO authenticated USING (true);

DROP POLICY IF EXISTS "Enable read access for all users" ON recettes_etiquettes;
DROP POLICY IF EXISTS "Enable insert for authenticated users only" ON recettes_etiquettes;
DROP POLICY IF EXISTS "Update recettes_etiquettes" ON recettes_etiquettes;
DROP POLICY IF EXISTS "Delete recettes_etiquettes" ON recettes_etiquettes;

CREATE POLICY "Enable read access for all users" ON recettes_etiquettes
    FOR SELECT TO public USING (true);

CREATE POLICY "Enable insert for authenticated users only" ON recettes_etiquettes
    FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "Update recettes_etiquettes" ON recettes_etiquettes
    FOR UPDATE TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "Delete recettes_etiquettes" ON recettes_etiquettes
    FOR DELETE TO authenticated USING (true);
